import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Loader2, Plus, Trash2 } from 'lucide-react'
import { queryKeys } from '@/lib/api/query-keys'
import { useToastMutation } from '@/hooks/use-toast-mutation'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { ConfirmDangerDialog } from '@/components/confirm-danger-dialog'
import {
  deleteWorkCitation,
  listCitationStyles,
  listWorkCitations,
  saveWorkCitation,
  type WorkCitation,
} from '@/features/citation-styles/api'

/**
 * La cita de este trabajo en cada estilo.
 *
 * El BibTeX que genera el sistema sigue estando; esto es para cuando la editorial
 * publica una forma de citar concreta y quieres ofrecerla tal cual.
 *
 * Se guarda por separado del resto del formulario: cada cita es un registro propio y
 * escribir una no debería obligar a guardar el trabajo entero.
 */

type Props = { workId: string }

export function CitationsSection({ workId }: Props) {
  const [estiloElegido, setEstiloElegido] = useState('')
  const [texto, setTexto] = useState('')
  const [borrando, setBorrando] = useState<WorkCitation | null>(null)

  const { data: estilos } = useQuery({
    queryKey: queryKeys.citationStyles.list(true),
    queryFn: () => listCitationStyles(true),
  })

  const { data: citas } = useQuery({
    queryKey: queryKeys.workCitations.byWork(workId),
    queryFn: () => listWorkCitations(workId),
  })

  const guardadas = citas ?? []
  const refresca = [queryKeys.workCitations.byWork(workId)]

  const guardar = useToastMutation({
    mutationFn: ({ styleId, content }: { styleId: string; content: string }) =>
      saveWorkCitation(workId, styleId, content),
    invalidates: refresca,
    success: 'Citation saved.',
    onSuccess: () => {
      setEstiloElegido('')
      setTexto('')
    },
  })

  const borrar = useToastMutation({
    mutationFn: (styleId: string) => deleteWorkCitation(workId, styleId),
    invalidates: refresca,
    success: 'Citation removed.',
    onSuccess: () => {
      setBorrando(null)
    },
    onError: () => {
      setBorrando(null)
    },
  })

  // Un estilo que ya tiene cita no se ofrece otra vez: para cambiarla se edita la que
  // hay, que es lo que se espera al ver el texto delante.
  const disponibles = (estilos ?? []).filter(
    (estilo) => !guardadas.some((cita) => cita.citationStyleId === estilo.id)
  )

  return (
    <div className='grid gap-3'>
      <div>
        <h3 className='font-medium'>Citations by style</h3>
        <p className='text-sm text-muted-foreground'>
          How this work is cited in each format. The BibTeX is generated on its
          own.
        </p>
      </div>

      {guardadas.length === 0 ? (
        <p className='rounded-md border border-dashed p-3 text-center text-sm text-muted-foreground'>
          No citations written. The one generated by the system will be used.
        </p>
      ) : (
        <ul className='grid gap-2'>
          {guardadas.map((cita) => (
            <li
              key={cita.id}
              className='grid gap-2 rounded-md border px-3 py-2'
            >
              <div className='flex items-center justify-between gap-2'>
                <Label htmlFor={`cita-${cita.id}`}>{cita.styleName}</Label>
                <Button
                  type='button'
                  variant='ghost'
                  size='icon'
                  aria-label={`Remove the ${cita.styleName} citation`}
                  onClick={() => {
                    setBorrando(cita)
                  }}
                >
                  <Trash2 className='size-4' />
                </Button>
              </div>
              <Textarea
                id={`cita-${cita.id}`}
                rows={2}
                defaultValue={cita.content}
                onBlur={(evento) => {
                  // Se guarda al salir del campo: escribir una cita no deberia obligar
                  // a pulsar un boton por cada estilo.
                  const nuevo = evento.target.value.trim()
                  if (nuevo !== '' && nuevo !== cita.content) {
                    guardar.mutate({
                      styleId: cita.citationStyleId,
                      content: nuevo,
                    })
                  }
                }}
              />
            </li>
          ))}
        </ul>
      )}

      {disponibles.length > 0 && (
        <div className='grid gap-2 rounded-md border p-3'>
          <Label htmlFor='nuevo-estilo'>Add a citation</Label>
          <Select value={estiloElegido} onValueChange={setEstiloElegido}>
            <SelectTrigger id='nuevo-estilo' className='sm:max-w-xs'>
              <SelectValue placeholder='Choose a style' />
            </SelectTrigger>
            <SelectContent>
              {disponibles.map((estilo) => (
                <SelectItem key={estilo.id} value={estilo.id}>
                  {estilo.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {estiloElegido !== '' && (
            <>
              <Textarea
                rows={2}
                placeholder='Paste the citation here exactly as the publisher writes it.'
                aria-label='Citation text'
                value={texto}
                onChange={(evento) => {
                  setTexto(evento.target.value)
                }}
              />
              <div className='flex justify-end'>
                <Button
                  type='button'
                  size='sm'
                  disabled={texto.trim() === '' || guardar.isPending}
                  onClick={() => {
                    guardar.mutate({
                      styleId: estiloElegido,
                      content: texto.trim(),
                    })
                  }}
                >
                  {guardar.isPending ? (
                    <Loader2 className='animate-spin' />
                  ) : (
                    <Plus />
                  )}
                  Add
                </Button>
              </div>
            </>
          )}
        </div>
      )}

      {borrando !== null && (
        <ConfirmDangerDialog
          open
          onOpenChange={(abierto) => {
            if (!abierto) setBorrando(null)
          }}
          requireTypedName={false}
          name={borrando.styleName}
          title={`Remove the ${borrando.styleName} citation`}
          description='The citation generated by the system will be used again.'
          confirmText='Remove'
          isLoading={borrar.isPending}
          onConfirm={() => {
            borrar.mutate(borrando.citationStyleId)
          }}
        />
      )}
    </div>
  )
}
