/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AdminWorksIndexRouteImport } from './routes/admin/works/index'
import { Route as AdminWorkTypesIndexRouteImport } from './routes/admin/work-types/index'
import { Route as AdminVenuesIndexRouteImport } from './routes/admin/venues/index'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminSiteSettingsIndexRouteImport } from './routes/admin/site-settings/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminPersonsIndexRouteImport } from './routes/admin/persons/index'
import { Route as AdminPersonLinksIndexRouteImport } from './routes/admin/person-links/index'
import { Route as AdminPageContentIndexRouteImport } from './routes/admin/page-content/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminInstitutionsIndexRouteImport } from './routes/admin/institutions/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminDepartmentsIndexRouteImport } from './routes/admin/departments/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCitationStylesIndexRouteImport } from './routes/admin/citation-styles/index'
import { Route as AdminCatalogsIndexRouteImport } from './routes/admin/catalogs/index'
import { Route as AdminAuditLogIndexRouteImport } from './routes/admin/audit-log/index'
import { Route as AdminAffiliationsIndexRouteImport } from './routes/admin/affiliations/index'
import { Route as AdminAcademicStatusesIndexRouteImport } from './routes/admin/academic-statuses/index'
import { Route as PublicTeachingIndexRouteImport } from './routes/_public/teaching/index'
import { Route as PublicResearchIndexRouteImport } from './routes/_public/research/index'
import { Route as PublicNewsIndexRouteImport } from './routes/_public/news/index'
import { Route as PublicEventsIndexRouteImport } from './routes/_public/events/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as AdminWorksNewRouteImport } from './routes/admin/works/new'
import { Route as AdminWorksWorkIdRouteImport } from './routes/admin/works/$workId'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events/new'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events/$eventId'
import { Route as AdminErrorsErrorRouteImport } from './routes/admin/errors/$error'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses/$courseId'
import { Route as PublicTeachingSlugRouteImport } from './routes/_public/teaching/$slug'
import { Route as PublicResearchSlugRouteImport } from './routes/_public/research/$slug'
import { Route as PublicNewsSlugRouteImport } from './routes/_public/news/$slug'
import { Route as PublicEventsSlugRouteImport } from './routes/_public/events/$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as AdminPostsKindIndexRouteImport } from './routes/admin/posts/$kind/index'
import { Route as AdminPostsKindNewRouteImport } from './routes/admin/posts/$kind/new'
import { Route as AdminPostsKindPostIdRouteImport } from './routes/admin/posts/$kind/$postId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorksIndexRoute = AdminWorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorkTypesIndexRoute = AdminWorkTypesIndexRouteImport.update({
  id: '/work-types/',
  path: '/work-types/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVenuesIndexRoute = AdminVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteSettingsIndexRoute = AdminSiteSettingsIndexRouteImport.update({
  id: '/site-settings/',
  path: '/site-settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPersonsIndexRoute = AdminPersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPersonLinksIndexRoute = AdminPersonLinksIndexRouteImport.update({
  id: '/person-links/',
  path: '/person-links/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPageContentIndexRoute = AdminPageContentIndexRouteImport.update({
  id: '/page-content/',
  path: '/page-content/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstitutionsIndexRoute = AdminInstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCitationStylesIndexRoute =
  AdminCitationStylesIndexRouteImport.update({
    id: '/citation-styles/',
    path: '/citation-styles/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCatalogsIndexRoute = AdminCatalogsIndexRouteImport.update({
  id: '/catalogs/',
  path: '/catalogs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogIndexRoute = AdminAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAffiliationsIndexRoute = AdminAffiliationsIndexRouteImport.update({
  id: '/affiliations/',
  path: '/affiliations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAcademicStatusesIndexRoute =
  AdminAcademicStatusesIndexRouteImport.update({
    id: '/academic-statuses/',
    path: '/academic-statuses/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const PublicTeachingIndexRoute = PublicTeachingIndexRouteImport.update({
  id: '/teaching/',
  path: '/teaching/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResearchIndexRoute = PublicResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEventsIndexRoute = PublicEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminWorksNewRoute = AdminWorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorksWorkIdRoute = AdminWorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminErrorsErrorRoute = AdminErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicTeachingSlugRoute = PublicTeachingSlugRouteImport.update({
  id: '/teaching/$slug',
  path: '/teaching/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResearchSlugRoute = PublicResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEventsSlugRoute = PublicEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminPostsKindIndexRoute = AdminPostsKindIndexRouteImport.update({
  id: '/posts/$kind/',
  path: '/posts/$kind/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsKindNewRoute = AdminPostsKindNewRouteImport.update({
  id: '/posts/$kind/new',
  path: '/posts/$kind/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsKindPostIdRoute = AdminPostsKindPostIdRouteImport.update({
  id: '/posts/$kind/$postId',
  path: '/posts/$kind/$postId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/research/$slug': typeof PublicResearchSlugRoute
  '/teaching/$slug': typeof PublicTeachingSlugRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/works/$workId': typeof AdminWorksWorkIdRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/events/': typeof PublicEventsIndexRoute
  '/news/': typeof PublicNewsIndexRoute
  '/research/': typeof PublicResearchIndexRoute
  '/teaching/': typeof PublicTeachingIndexRoute
  '/admin/academic-statuses/': typeof AdminAcademicStatusesIndexRoute
  '/admin/affiliations/': typeof AdminAffiliationsIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/catalogs/': typeof AdminCatalogsIndexRoute
  '/admin/citation-styles/': typeof AdminCitationStylesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/page-content/': typeof AdminPageContentIndexRoute
  '/admin/person-links/': typeof AdminPersonLinksIndexRoute
  '/admin/persons/': typeof AdminPersonsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/site-settings/': typeof AdminSiteSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/venues/': typeof AdminVenuesIndexRoute
  '/admin/work-types/': typeof AdminWorkTypesIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/admin/posts/$kind/$postId': typeof AdminPostsKindPostIdRoute
  '/admin/posts/$kind/new': typeof AdminPostsKindNewRoute
  '/admin/posts/$kind/': typeof AdminPostsKindIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/research/$slug': typeof PublicResearchSlugRoute
  '/teaching/$slug': typeof PublicTeachingSlugRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/works/$workId': typeof AdminWorksWorkIdRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/blog': typeof PublicBlogIndexRoute
  '/events': typeof PublicEventsIndexRoute
  '/news': typeof PublicNewsIndexRoute
  '/research': typeof PublicResearchIndexRoute
  '/teaching': typeof PublicTeachingIndexRoute
  '/admin/academic-statuses': typeof AdminAcademicStatusesIndexRoute
  '/admin/affiliations': typeof AdminAffiliationsIndexRoute
  '/admin/audit-log': typeof AdminAuditLogIndexRoute
  '/admin/catalogs': typeof AdminCatalogsIndexRoute
  '/admin/citation-styles': typeof AdminCitationStylesIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/institutions': typeof AdminInstitutionsIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/page-content': typeof AdminPageContentIndexRoute
  '/admin/person-links': typeof AdminPersonLinksIndexRoute
  '/admin/persons': typeof AdminPersonsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/site-settings': typeof AdminSiteSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/venues': typeof AdminVenuesIndexRoute
  '/admin/work-types': typeof AdminWorkTypesIndexRoute
  '/admin/works': typeof AdminWorksIndexRoute
  '/admin/posts/$kind/$postId': typeof AdminPostsKindPostIdRoute
  '/admin/posts/$kind/new': typeof AdminPostsKindNewRoute
  '/admin/posts/$kind': typeof AdminPostsKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/events/$slug': typeof PublicEventsSlugRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/_public/research/$slug': typeof PublicResearchSlugRoute
  '/_public/teaching/$slug': typeof PublicTeachingSlugRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/works/$workId': typeof AdminWorksWorkIdRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/events/': typeof PublicEventsIndexRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/_public/research/': typeof PublicResearchIndexRoute
  '/_public/teaching/': typeof PublicTeachingIndexRoute
  '/admin/academic-statuses/': typeof AdminAcademicStatusesIndexRoute
  '/admin/affiliations/': typeof AdminAffiliationsIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/catalogs/': typeof AdminCatalogsIndexRoute
  '/admin/citation-styles/': typeof AdminCitationStylesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/page-content/': typeof AdminPageContentIndexRoute
  '/admin/person-links/': typeof AdminPersonLinksIndexRoute
  '/admin/persons/': typeof AdminPersonsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/site-settings/': typeof AdminSiteSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/venues/': typeof AdminVenuesIndexRoute
  '/admin/work-types/': typeof AdminWorkTypesIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/admin/posts/$kind/$postId': typeof AdminPostsKindPostIdRoute
  '/admin/posts/$kind/new': typeof AdminPostsKindNewRoute
  '/admin/posts/$kind/': typeof AdminPostsKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/'
    | '/blog/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/research/$slug'
    | '/teaching/$slug'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/errors/$error'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/works/$workId'
    | '/admin/works/new'
    | '/blog/'
    | '/events/'
    | '/news/'
    | '/research/'
    | '/teaching/'
    | '/admin/academic-statuses/'
    | '/admin/affiliations/'
    | '/admin/audit-log/'
    | '/admin/catalogs/'
    | '/admin/citation-styles/'
    | '/admin/courses/'
    | '/admin/departments/'
    | '/admin/events/'
    | '/admin/institutions/'
    | '/admin/media/'
    | '/admin/page-content/'
    | '/admin/person-links/'
    | '/admin/persons/'
    | '/admin/profile/'
    | '/admin/site-settings/'
    | '/admin/tags/'
    | '/admin/venues/'
    | '/admin/work-types/'
    | '/admin/works/'
    | '/admin/posts/$kind/$postId'
    | '/admin/posts/$kind/new'
    | '/admin/posts/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/research/$slug'
    | '/teaching/$slug'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/errors/$error'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/works/$workId'
    | '/admin/works/new'
    | '/blog'
    | '/events'
    | '/news'
    | '/research'
    | '/teaching'
    | '/admin/academic-statuses'
    | '/admin/affiliations'
    | '/admin/audit-log'
    | '/admin/catalogs'
    | '/admin/citation-styles'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/institutions'
    | '/admin/media'
    | '/admin/page-content'
    | '/admin/person-links'
    | '/admin/persons'
    | '/admin/profile'
    | '/admin/site-settings'
    | '/admin/tags'
    | '/admin/venues'
    | '/admin/work-types'
    | '/admin/works'
    | '/admin/posts/$kind/$postId'
    | '/admin/posts/$kind/new'
    | '/admin/posts/$kind'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_public/'
    | '/admin/'
    | '/_public/blog/$slug'
    | '/_public/events/$slug'
    | '/_public/news/$slug'
    | '/_public/research/$slug'
    | '/_public/teaching/$slug'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/errors/$error'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/works/$workId'
    | '/admin/works/new'
    | '/_public/blog/'
    | '/_public/events/'
    | '/_public/news/'
    | '/_public/research/'
    | '/_public/teaching/'
    | '/admin/academic-statuses/'
    | '/admin/affiliations/'
    | '/admin/audit-log/'
    | '/admin/catalogs/'
    | '/admin/citation-styles/'
    | '/admin/courses/'
    | '/admin/departments/'
    | '/admin/events/'
    | '/admin/institutions/'
    | '/admin/media/'
    | '/admin/page-content/'
    | '/admin/person-links/'
    | '/admin/persons/'
    | '/admin/profile/'
    | '/admin/site-settings/'
    | '/admin/tags/'
    | '/admin/venues/'
    | '/admin/work-types/'
    | '/admin/works/'
    | '/admin/posts/$kind/$postId'
    | '/admin/posts/$kind/new'
    | '/admin/posts/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/works/': {
      id: '/admin/works/'
      path: '/works'
      fullPath: '/admin/works/'
      preLoaderRoute: typeof AdminWorksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/work-types/': {
      id: '/admin/work-types/'
      path: '/work-types'
      fullPath: '/admin/work-types/'
      preLoaderRoute: typeof AdminWorkTypesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/venues/': {
      id: '/admin/venues/'
      path: '/venues'
      fullPath: '/admin/venues/'
      preLoaderRoute: typeof AdminVenuesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site-settings/': {
      id: '/admin/site-settings/'
      path: '/site-settings'
      fullPath: '/admin/site-settings/'
      preLoaderRoute: typeof AdminSiteSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/persons/': {
      id: '/admin/persons/'
      path: '/persons'
      fullPath: '/admin/persons/'
      preLoaderRoute: typeof AdminPersonsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/person-links/': {
      id: '/admin/person-links/'
      path: '/person-links'
      fullPath: '/admin/person-links/'
      preLoaderRoute: typeof AdminPersonLinksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/page-content/': {
      id: '/admin/page-content/'
      path: '/page-content'
      fullPath: '/admin/page-content/'
      preLoaderRoute: typeof AdminPageContentIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/institutions/': {
      id: '/admin/institutions/'
      path: '/institutions'
      fullPath: '/admin/institutions/'
      preLoaderRoute: typeof AdminInstitutionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/departments/': {
      id: '/admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments/'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/citation-styles/': {
      id: '/admin/citation-styles/'
      path: '/citation-styles'
      fullPath: '/admin/citation-styles/'
      preLoaderRoute: typeof AdminCitationStylesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalogs/': {
      id: '/admin/catalogs/'
      path: '/catalogs'
      fullPath: '/admin/catalogs/'
      preLoaderRoute: typeof AdminCatalogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log/': {
      id: '/admin/audit-log/'
      path: '/audit-log'
      fullPath: '/admin/audit-log/'
      preLoaderRoute: typeof AdminAuditLogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/affiliations/': {
      id: '/admin/affiliations/'
      path: '/affiliations'
      fullPath: '/admin/affiliations/'
      preLoaderRoute: typeof AdminAffiliationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/academic-statuses/': {
      id: '/admin/academic-statuses/'
      path: '/academic-statuses'
      fullPath: '/admin/academic-statuses/'
      preLoaderRoute: typeof AdminAcademicStatusesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/teaching/': {
      id: '/_public/teaching/'
      path: '/teaching'
      fullPath: '/teaching/'
      preLoaderRoute: typeof PublicTeachingIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/research/': {
      id: '/_public/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof PublicResearchIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/events/': {
      id: '/_public/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof PublicEventsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/works/new': {
      id: '/admin/works/new'
      path: '/works/new'
      fullPath: '/admin/works/new'
      preLoaderRoute: typeof AdminWorksNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/works/$workId': {
      id: '/admin/works/$workId'
      path: '/works/$workId'
      fullPath: '/admin/works/$workId'
      preLoaderRoute: typeof AdminWorksWorkIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/errors/$error': {
      id: '/admin/errors/$error'
      path: '/errors/$error'
      fullPath: '/admin/errors/$error'
      preLoaderRoute: typeof AdminErrorsErrorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/teaching/$slug': {
      id: '/_public/teaching/$slug'
      path: '/teaching/$slug'
      fullPath: '/teaching/$slug'
      preLoaderRoute: typeof PublicTeachingSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/research/$slug': {
      id: '/_public/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof PublicResearchSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/events/$slug': {
      id: '/_public/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof PublicEventsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/posts/$kind/': {
      id: '/admin/posts/$kind/'
      path: '/posts/$kind'
      fullPath: '/admin/posts/$kind/'
      preLoaderRoute: typeof AdminPostsKindIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$kind/new': {
      id: '/admin/posts/$kind/new'
      path: '/posts/$kind/new'
      fullPath: '/admin/posts/$kind/new'
      preLoaderRoute: typeof AdminPostsKindNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$kind/$postId': {
      id: '/admin/posts/$kind/$postId'
      path: '/posts/$kind/$postId'
      fullPath: '/admin/posts/$kind/$postId'
      preLoaderRoute: typeof AdminPostsKindPostIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicEventsSlugRoute: typeof PublicEventsSlugRoute
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
  PublicResearchSlugRoute: typeof PublicResearchSlugRoute
  PublicTeachingSlugRoute: typeof PublicTeachingSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicEventsIndexRoute: typeof PublicEventsIndexRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
  PublicResearchIndexRoute: typeof PublicResearchIndexRoute
  PublicTeachingIndexRoute: typeof PublicTeachingIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicEventsSlugRoute: PublicEventsSlugRoute,
  PublicNewsSlugRoute: PublicNewsSlugRoute,
  PublicResearchSlugRoute: PublicResearchSlugRoute,
  PublicTeachingSlugRoute: PublicTeachingSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicEventsIndexRoute: PublicEventsIndexRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
  PublicResearchIndexRoute: PublicResearchIndexRoute,
  PublicTeachingIndexRoute: PublicTeachingIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminErrorsErrorRoute: typeof AdminErrorsErrorRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminWorksWorkIdRoute: typeof AdminWorksWorkIdRoute
  AdminWorksNewRoute: typeof AdminWorksNewRoute
  AdminAcademicStatusesIndexRoute: typeof AdminAcademicStatusesIndexRoute
  AdminAffiliationsIndexRoute: typeof AdminAffiliationsIndexRoute
  AdminAuditLogIndexRoute: typeof AdminAuditLogIndexRoute
  AdminCatalogsIndexRoute: typeof AdminCatalogsIndexRoute
  AdminCitationStylesIndexRoute: typeof AdminCitationStylesIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminInstitutionsIndexRoute: typeof AdminInstitutionsIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminPageContentIndexRoute: typeof AdminPageContentIndexRoute
  AdminPersonLinksIndexRoute: typeof AdminPersonLinksIndexRoute
  AdminPersonsIndexRoute: typeof AdminPersonsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminSiteSettingsIndexRoute: typeof AdminSiteSettingsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
  AdminVenuesIndexRoute: typeof AdminVenuesIndexRoute
  AdminWorkTypesIndexRoute: typeof AdminWorkTypesIndexRoute
  AdminWorksIndexRoute: typeof AdminWorksIndexRoute
  AdminPostsKindPostIdRoute: typeof AdminPostsKindPostIdRoute
  AdminPostsKindNewRoute: typeof AdminPostsKindNewRoute
  AdminPostsKindIndexRoute: typeof AdminPostsKindIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminErrorsErrorRoute: AdminErrorsErrorRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminWorksWorkIdRoute: AdminWorksWorkIdRoute,
  AdminWorksNewRoute: AdminWorksNewRoute,
  AdminAcademicStatusesIndexRoute: AdminAcademicStatusesIndexRoute,
  AdminAffiliationsIndexRoute: AdminAffiliationsIndexRoute,
  AdminAuditLogIndexRoute: AdminAuditLogIndexRoute,
  AdminCatalogsIndexRoute: AdminCatalogsIndexRoute,
  AdminCitationStylesIndexRoute: AdminCitationStylesIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminInstitutionsIndexRoute: AdminInstitutionsIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminPageContentIndexRoute: AdminPageContentIndexRoute,
  AdminPersonLinksIndexRoute: AdminPersonLinksIndexRoute,
  AdminPersonsIndexRoute: AdminPersonsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminSiteSettingsIndexRoute: AdminSiteSettingsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
  AdminVenuesIndexRoute: AdminVenuesIndexRoute,
  AdminWorkTypesIndexRoute: AdminWorkTypesIndexRoute,
  AdminWorksIndexRoute: AdminWorksIndexRoute,
  AdminPostsKindPostIdRoute: AdminPostsKindPostIdRoute,
  AdminPostsKindNewRoute: AdminPostsKindNewRoute,
  AdminPostsKindIndexRoute: AdminPostsKindIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
